// let text = "I love JavaScript!";
// console.log(text.match(/javascript/i));
// let text = "I love React and JavaScript!";
// console.log(text.match(/javascript|nodejs|react/gi));
//let text = "0t";
// console.log(text.match(/[a-zA-Z]/));
// console.log(text.match(/[a-z]/i));

// let text = "äé!.";
// console.log(text.match(/./g));
// let text = "Just some text.";
// console.log(text.match(/\./g));
// let text = "I'm 29 years old.";
// console.log(text.match(/\d/g))
// let text = "Coding is a lot of fun!";
// console.log(text.match(/\s/g)); 
// let text = "In the end or at the inbeginning?";
// console.log(text.match(/\bin/gi));
// let nr = 357;
// console.log(nr.match(/3/g));
// 0
// let text = "I love JavaScript!";
// console.log(text.match(/[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]/g));
// let text = "You are doing great!";
// console.log(text.match(/n?g/gi));
// let text = "123123123a";
// console.log(text.match(/(123)*a/));
// let text = "abcabcabc";
// console.log(text.match(/(abc){1,2}/));
// let text = "I love JavaScript!";
// console.log(text.match(/(?<language>javascript)/i));
// let text = "That's not the case.";
// console.log(text.search(/Case/i));
// let text = "Coding is fun. Coding opens up a lot of opportunities.";
// console.log(text.replace(/Coding/g, "JavaScript"));
let emailPattern = /([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/g;
let validEmail = "maaike_1234@email.com";
let invalidEmail = "maaike@mail@.com";
console.log(validEmail.match(emailPattern));
console.log(invalidEmail.match(emailPattern));